<?php

namespace OC\PlatformBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getApplicationsWithAdvert($limit)
    {
        $qb = $this->createQueryBuilder('a');

        $qb
            ->innerJoin('a.advert', 'ad')
            ->addSelect('ad')
            ->orderBy('a.date', 'DESC')
            ->setMaxResults($limit)
        ;

        return $qb
            ->getQuery()
            ->getResult()
        ;


    }

    public function findApplicationsByAuthor($author)
    {
        $qb = $this->createQueryBuilder('a');

        $qb
            ->andWhere('a.author = :author')
            ->setParameter('author',$author)
        ;

        return $qb
            ->getQuery()
            ->getResult()
        ;
    }
}
